PRAGMA foreign_keys = OFF;

DROP TABLE IF EXISTS plays;
DROP TABLE IF EXISTS player;

PRAGMA foreign_keys = ON;

CREATE TABLE player (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name TEXT NOT NULL UNIQUE
);

CREATE TABLE plays (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	played_at TEXT NOT NULL,
	music_name TEXT NOT NULL,
	score INTEGER NOT NULL,
	player_id INTEGER NOT NULL,
	errors INTEGER NOT NULL DEFAULT 0,
	perfect_hits INTEGER NOT NULL DEFAULT 0,
	good_hits INTEGER NOT NULL DEFAULT 0,
	bad_hits INTEGER NOT NULL DEFAULT 0,
	FOREIGN KEY (player_id) REFERENCES player(id) ON DELETE CASCADE
);
